language: java
before_install:
  - wget https://services.gradle.org/distributions/gradle-6.4.1-bin.zip
  - unzip -d /opt/gradle gradle-6.4.1-bin.zip
  - export GRADLE_HOME=/opt/gradle/gradle-6.4.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - wget https://download.bell-sw.com/java/11.0.8+10/bellsoft-jdk11.0.8+10-linux-amd64.deb
  - sudo dpkg -i bellsoft-jdk11.0.8+10-linux-amd64.deb
  - export JAVA_HOME=/usr/lib/jvm/bellsoft-java11-amd64
  - export PATH=$JAVA_HOME/bin:$PATH