spring:
  application:
    name: mcn
  data:
    mongodb:
      uri: ${MONGODB_URI}
  mongock:
    change-logs-scan-package:
      - me.local.mcn.changelogs
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
server:
  port: 8080